### ISSUE TITLE
[Bug] URL must be a Vailed URI

### ISSUE THREAD

**Issue by LedgendODST** [smarterToby/ValorantRPC#9]
### Describe your issue

Hello, 
i got a issue the Programm tells me as in the Screenshot the URL must be a vailed URI can you fix this or tell me how to fix this? 

many thanks!

### Which version of ValorantRPC are you using?

1.1.2

### Operating System

Windows 10 64Bit

### Valorant Version

9.02

### Put here any screenshots or videos (optional)

![ValoStatus](https://github.com/user-attachments/assets/3d59c80d-812a-4015-92c0-d4cac4aab90f)

### Would you like to work on this issue?

None

**Comment by pranavid22** [comment]
Solution: 
1)Verify that the URL you're providing is a valid web address. It should start with http:// or https://, followed by a domain name and optionally a path.
2)If the URL contains special characters (like spaces or non-ASCII characters), they should be URL-encoded.
3) Make sure there are no typos or special characters in the URL that could invalidate it.
4)The url field must be a properly formatted string.

**Comment by LedgendODST** [comment]
what URL? i followed the programm instructions and it said only open it and if what which URL? i never have any chance on putting an URL in

**Comment by reussio** [comment]
Should be fixed. I guess 😅
You can download the newst version here: https://github.com/smarterToby/ValorantRPC/releases/tag/v1.1.4

**Comment by LedgendODST** [comment]
![ValoSelect](https://github.com/user-attachments/assets/ecc6580a-2fb6-46a6-a551-c11cdc8c8e23)
i think the programm is not updating or is it something on my side i need to change?
it Shows im always in the Lobby

**Comment by reussio** [comment]
Normally you don't have to do anything. Have you restarted the application

**Comment by LedgendODST** [comment]
i restarted it and now it says Valorant Config Initalized but im still in the Lobbys but im in game again.

i restarted Valorant and the application

**Comment by reussio** [comment]
Ok, can you run this debug version. This prints the state of your game in the console. Like Ingame, Prematch, Menu - this should normaly change
Run it please if you in the lobby and you are starting a custom match. 
Please send me a copy of the logs afterwards or tell me if it changed
[ValorantRPC-Debug-SessionLoopState.zip](https://github.com/user-attachments/files/16495980/ValorantRPC-Debug-SessionLoopState.zip)

**Comment by LedgendODST** [comment]
> Ok, can you run this debug version. This prints the state of your game in the console. Like Ingame, Prematch, Menu - this should normaly change Run it please if you in the lobby and you are starting a custom match. Please send me a copy of the logs afterwards or tell me if it changed [ValorantRPC-Debug-SessionLoopState.zip](https://github.com/user-attachments/files/16495980/ValorantRPC-Debug-SessionLoopState.zip)

it does not print any logs and this is still not working (Nothing changed same error), or is the Log file in my App Data?

**Comment by reussio** [comment]
strange. try this one
[valorant-rpc-debug.zip](https://github.com/user-attachments/files/16498746/valorant-rpc-debug.zip)

**Comment by LedgendODST** [comment]
![image](https://github.com/user-attachments/assets/5bb90d62-2df8-43cd-8582-87f9587eeb37)
Still not working this is the Log. there is no file Log

i was in Game and in Lobby but nothing changed in the presence

**Comment by reussio** [comment]
do you appear offline in the friend list?

**Comment by LedgendODST** [comment]
> do you appear offline in the friend list?

yes, do you think that is the Problem?

**Comment by reussio** [comment]
Yes, I'm pretty sure of that. To put it simply, I can only access some data, such as the current score in the match, via the friendlist

**Comment by LedgendODST** [comment]
> Yes, I'm pretty sure of that. To put it simply, I can only access some data, such as the current score in the match, via the friendlist

Yeah, without being offline it works im sorry for wasting your time enjoy the rest of the week.

**Comment by reussio** [comment]
> > Yes, I'm pretty sure of that. To put it simply, I can only access some data, such as the current score in the match, via the friendlist
> 
> Yeah, without being offline it works im sorry for wasting your time enjoy the rest of the week.

No problem. At least I've updated the app to the latest version and added the new map.
You are welcome to download it here:
[ValorantRPC 1.1.5](https://github.com/smarterToby/ValorantRPC/releases/tag/v1.1.5)
